name: CI Backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12" 

      - name: Instalar dependencias del backend
        run: |
          cd backend
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ejecutar pruebas del backend
        env:
            SECRET_KEY: "dev-secret-key-12345"
            DEBUG: "True"
            DB_NAME: "sgpi_db"
            DB_USER: "william"
            DB_PASSWORD: "test_password"
            DB_HOST: "localhost"
            DB_PORT: "5432"
            # Añadir cualquier otra variable del settings.py (DB_NAME, etc.)
        run: |
          cd backend
          # Archivo manage.py en la carpeta backend
          python manage.py test
