name: CI Frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v4

      - name: Instalar Node LTS
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          # Esto ayuda a que npm install sea más rápido en ejecuciones futuras
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Instalar dependencias
        run: |
          cd frontend
          npm ci # 'npm ci' es más rápido y limpio que 'npm install' en servidores de CI

      - name: Verificar compilación (Build)
        run: |
          cd frontend
          npm run build

      - name: Ejecutar pruebas
        run: |
          cd frontend
          # --run para que Vitest no se quede en modo "watch"
          npm test -- --run